# Generated by Django 5.2 on 2025-04-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='embedding',
            field=models.JSONField(),
        ),
    ]
